# Generated by Django 5.1.7 on 2025-04-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
