# Generated by Django 5.1.7 on 2025-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_video_url_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
