# Generated by Django 5.2.5 on 2025-09-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_poem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'verbose_name': 'Стихотворение', 'verbose_name_plural': 'Стихи'},
        ),
        migrations.AddField(
            model_name='image',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
