# Generated by Django 4.2.20 on 2025-04-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_poem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'verbose_name': 'Стихотворение', 'verbose_name_plural': 'Стихи'},
        ),
    ]
