# Generated by Django 5.1.7 on 2025-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbookentry',
            options={'verbose_name': 'Запись в гостевой книге', 'verbose_name_plural': 'Записи в гостевой книге'},
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='memory',
            field=models.TextField(verbose_name='Воспоминание'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Роль'),
        ),
    ]
