# Generated by Django 5.1.7 on 2025-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_guestbookentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbookentry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guestbookentry',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guestbookentry',
            name='role',
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
