# Generated by Django 5.1.7 on 2025-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_remove_guestbookentry_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('memory', models.TextField(verbose_name='Воспоминание')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Фото')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
            ],
            options={
                'verbose_name': 'Воспоминание',
                'verbose_name_plural': 'Воспоминания',
            },
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
